esphome:
  name: balance01

# ESP32 Platform
# https://esphome.io/components/esp32.html
esp32:
  # https://registry.platformio.org/platforms/platformio/espressif32/boards?version=5.3.0
  # https://docs.platformio.org/en/latest/boards/espressif32/nodemcu-32s.html
  board: nodemcu-32s
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "eduroam"
  password: "password"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "Balance01 Fallback Hotspot"
    password: "QFQfkY04Qboh"

captive_portal:

# https://esphome.io/components/sensor/
switch:
  # HX711 modules
  - platform: gpio
    name: "Weight U1"
    pin: GPIO32
  - platform: gpio
    name: "Weight U2"
    pin: GPIO22
  - platform: gpio
    name: "Weight U3"
    pin: GPIO16
  - platform: gpio
    name: "Weight U4"
    pin: GPIO18
  - platform: gpio
    name: "Weight U5"
    pin: GPIO21
  - platform: gpio
    name: "Weight U6"
    pin: GPIO25
