# GitHub Actions workflow
# https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions
name: ESPHome validation

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  lint:
    runs-on: "ubuntu-24.04"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5.2.0
        with:
          python-version: "3.12"
      - run: pip install -r requirements.txt
      # https://esphome.io/guides/cli.html#config-command
      - name: esphome config
        run: | 
          for path in *.yaml
          do
            esphome config $path
          done
